// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  16

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    jex_sc_governance
    (
        init => init
        upgrade => upgrade
        createProposal => create_proposal
        cleanup => cleanup
        setAdmin => set_admin
        vote => vote
        getProposals => get_proposals
        getVotingPower => get_voting_power
        getAdminAddress => admin_address
        getLockerScAddress => sc_locker_address
        getProposal => proposal
        getProposalNftCollectionId => proposal_nft_collection_id
        getVoteResults => vote_results
        getVoters => voters
        hasVoted => has_voted
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
