// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    jex_sc_governance
    (
        init => init
        upgrade => upgrade
        createProposal => create_proposal
        setAdmin => set_admin
        getVotingPower => get_voting_power
        getAdminAddress => admin_address
        getLockerScAddress => sc_locker_address
        getProposal => proposal
        getProposalNftCollectionId => proposal_nft_collection_id
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
